version: '3.3'
services:
  knotdns-pri:
    container_name: knot-pri
    image: 'hexim/knotdns:3.2.2'
    ports:
     - "5053:53/tcp"
     - "5053:53/udp"
     - "8853:853/udp"
    stdin_open: true
    volumes:
     - ./knot-pri/etc:/etc/knot
     - ./knot-pri/var/lib:/var/lib/knot
    networks:
      test:
        ipv4_address: 172.1.0.2
  knotdns-sec:
    container_name: knot-sec
    image: 'hexim/knotdns:latest'
    ports:
     - "5054:53/tcp"
     - "5054:53/udp"
     - "8854:853/udp"
    stdin_open: true
    volumes:
     - /opt/knot-sec/etc:/etc/knot
     - /opt/knot-sec/var/lib:/var/lib/knot
    networks:
      test:
        ipv4_address: 172.1.0.3
etworks:
  test:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.1.0.0/24
